/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista.gerente;

import ec.edu.ups.controlador.ControladorMesero;
import ec.edu.ups.modelo.Mesero;
import java.awt.event.KeyEvent;
import java.util.ResourceBundle;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class VentanaEditarMesero extends javax.swing.JInternalFrame {

    private ControladorMesero controladorMesero;
    private ResourceBundle mensajes;
    private JLabel titulo;
    private String nofound;
    private String bumesero;
    private String actmesero;
    private String errorpass;
    private String pass;

    /**
     * Creates new form VentanaEditarMesero
     */
    public VentanaEditarMesero(ControladorMesero controladorMesero, ResourceBundle mensajes) {
        titulo = new JLabel(mensajes.getString("mesero.editar"));
        initComponents();
        this.controladorMesero = controladorMesero;
        this.mensajes = mensajes;
        cambiarIdiomas(mensajes);
        bActualizar.setEnabled(false);
    }

    public void cambiarIdiomas(ResourceBundle mensajes) {
        titulo.setText(mensajes.getString("mesero.editar"));
        nofound = mensajes.getString("option.nomesero");
        bumesero = mensajes.getString("mesero.buscar");
        actmesero = mensajes.getString("option.actmesero");
        errorpass = mensajes.getString("option.errorpass");
        pass = mensajes.getString("txt.contraseña");
        lCodigo.setText(mensajes.getString("txt.codigo"));
        lCedula.setText(mensajes.getString("cliente.cedula"));
        lNombre.setText(mensajes.getString("txt.nombre"));
        lDireccion.setText(mensajes.getString("cliente.direccion"));
        lTelefono.setText(mensajes.getString("cliente.telefono"));
        lPassActual.setText(mensajes.getString("txt.contrasenaactual"));
        lPassNueva.setText(mensajes.getString("txt.contrasenanueva"));
        bBuscar.setText(mensajes.getString("boton.buscar"));
        bActualizar.setText(mensajes.getString("boton.actualizar"));
        bCancelar.setText(mensajes.getString("boton.cancelar"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tCodigo = new javax.swing.JTextField();
        lCodigo = new javax.swing.JLabel();
        lCedula = new javax.swing.JLabel();
        tCedula = new javax.swing.JTextField();
        bBuscar = new javax.swing.JButton();
        lNombre = new javax.swing.JLabel();
        tNombre = new javax.swing.JTextField();
        tDireccion = new javax.swing.JTextField();
        lDireccion = new javax.swing.JLabel();
        lTelefono = new javax.swing.JLabel();
        tTelefono = new javax.swing.JTextField();
        bCancelar = new javax.swing.JButton();
        bActualizar = new javax.swing.JButton();
        lPassActual = new javax.swing.JLabel();
        tPassActual = new javax.swing.JTextField();
        tPassNueva = new javax.swing.JTextField();
        lPassNueva = new javax.swing.JLabel();

        setClosable(true);
        setTitle(titulo.getText());
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        lCodigo.setText("Código:");

        lCedula.setText("Cédula:");

        bBuscar.setText("Buscar");
        bBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarActionPerformed(evt);
            }
        });

        lNombre.setText("Nombre:");

        lDireccion.setText("Dirección:");

        lTelefono.setText("Teléfono:");

        bCancelar.setText("Cancelar");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        bActualizar.setText("Actualizar");
        bActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActualizarActionPerformed(evt);
            }
        });

        lPassActual.setText("Contraseña actual:");

        lPassNueva.setText("Contraseña nueva:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bActualizar)
                        .addGap(18, 18, 18)
                        .addComponent(bCancelar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 12, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(11, 11, 11)
                                    .addComponent(lCodigo)
                                    .addGap(18, 18, 18)
                                    .addComponent(tCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(26, 26, 26)
                                    .addComponent(bBuscar))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lDireccion, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lNombre, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lTelefono, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lCedula, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                                        .addComponent(tDireccion)
                                        .addComponent(tTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lPassNueva)
                                        .addGap(18, 18, 18)
                                        .addComponent(tPassNueva))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lPassActual)
                                        .addGap(18, 18, 18)
                                        .addComponent(tPassActual, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(50, 50, 50)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCodigo)
                    .addComponent(tCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCedula)
                    .addComponent(tCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNombre)
                    .addComponent(tNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lDireccion)
                    .addComponent(tDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lTelefono)
                    .addComponent(tTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lPassActual)
                    .addComponent(tPassActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lPassNueva)
                    .addComponent(tPassNueva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCancelar)
                    .addComponent(bActualizar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_bCancelarActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE && this.isFocusOwner()) {
            this.dispose();
        }
    }//GEN-LAST:event_formKeyPressed

    private void bBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarActionPerformed
        if (tCodigo.getText().equals("") == false) {
            int cod = Integer.parseInt(tCodigo.getText());
            Mesero buscarMesero = controladorMesero.read(cod);
            if (buscarMesero != null) {
                tCedula.setText(buscarMesero.getCedula());
                tNombre.setText(buscarMesero.getNombre());
                tDireccion.setText(buscarMesero.getDireccion());
                tTelefono.setText(buscarMesero.getTelefono());
                bActualizar.setEnabled(true);
            } else {
                tCedula.setText("");
                tNombre.setText("");
                tDireccion.setText("");
                tTelefono.setText("");
                JOptionPane.showMessageDialog(this,
                        nofound = mensajes.getString("option.nomesero"),
                        bumesero = mensajes.getString("mesero.buscar"),
                        JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Error", "Valor", JOptionPane.ERROR_MESSAGE);
            tCedula.setText("");
            tNombre.setText("");
            tDireccion.setText("");
            tTelefono.setText("");
        }
    }//GEN-LAST:event_bBuscarActionPerformed

    private void bActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActualizarActionPerformed
        int cod = Integer.parseInt(tCodigo.getText());
        Mesero editMesero = controladorMesero.read(cod);
        editMesero.setCodigo(Integer.parseInt(tCodigo.getText()));
        editMesero.setCedula(tCedula.getText());
        editMesero.setNombre(tNombre.getText());
        editMesero.setDireccion(tDireccion.getText());
        editMesero.setTelefono(tTelefono.getText());
        if (tPassActual.getText().equals(editMesero.getContraseña())) {
            editMesero.setContraseña(tPassNueva.getText());
            controladorMesero.update(editMesero);
            JOptionPane.showMessageDialog(this,
                    actmesero = mensajes.getString("option.actmesero"),
                    titulo.getText(), JOptionPane.INFORMATION_MESSAGE);
            tCodigo.setText("");
            tCedula.setText("");
            tNombre.setText("");
            tDireccion.setText("");
            tTelefono.setText("");
            tPassActual.setText("");
            tPassNueva.setText("");
        } else {
            JOptionPane.showMessageDialog(this,
                    errorpass = mensajes.getString("option.errorpass"),
                    pass = mensajes.getString("txt.contraseña"),
                    JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_bActualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bActualizar;
    private javax.swing.JButton bBuscar;
    private javax.swing.JButton bCancelar;
    private javax.swing.JLabel lCedula;
    private javax.swing.JLabel lCodigo;
    private javax.swing.JLabel lDireccion;
    private javax.swing.JLabel lNombre;
    private javax.swing.JLabel lPassActual;
    private javax.swing.JLabel lPassNueva;
    private javax.swing.JLabel lTelefono;
    private javax.swing.JTextField tCedula;
    private javax.swing.JTextField tCodigo;
    private javax.swing.JTextField tDireccion;
    private javax.swing.JTextField tNombre;
    private javax.swing.JTextField tPassActual;
    private javax.swing.JTextField tPassNueva;
    private javax.swing.JTextField tTelefono;
    // End of variables declaration//GEN-END:variables
}
