/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista.gerente;

import ec.edu.ups.controlador.ControladorProducto;
import ec.edu.ups.modelo.Categoria;
import ec.edu.ups.modelo.Producto;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.ResourceBundle;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author DELL
 */
public class VentanaEditarProducto extends javax.swing.JInternalFrame {

    private ControladorProducto controladorProducto;
    private Categoria categoria;
    private String ruta;
    private ResourceBundle mensajes;
    private JLabel titulo;
    private String entrada;
    private String plato;
    private String bebida;
    private String postre;
    private String nofound;
    private String bprod;
    private String actpr;

    /**
     * Creates new form VentanaEditarProducto
     */
    public VentanaEditarProducto(ControladorProducto controladorProducto, ResourceBundle mensajes) {
        titulo = new JLabel(mensajes.getString("producto.editar"));
        entrada = mensajes.getString("txt.entrada");
        plato = mensajes.getString("txt.plato");
        bebida = mensajes.getString("txt.bebida");
        postre = mensajes.getString("txt.postre");
        initComponents();
        this.controladorProducto = controladorProducto;
        this.mensajes = mensajes;
        cambiarIdiomas(mensajes);
        bActualizar.setEnabled(false);
    }

    public void cambiarIdiomas(ResourceBundle mensajes) {
        entrada = mensajes.getString("txt.entrada");
        plato = mensajes.getString("txt.plato");
        bebida = mensajes.getString("txt.bebida");
        postre = mensajes.getString("txt.postre");
        nofound = mensajes.getString("option.noprod");
        bprod = mensajes.getString("producto.buscar");
        actpr = mensajes.getString("option.actprod");
        titulo.setText(mensajes.getString("producto.editar"));
        lCodigo.setText(mensajes.getString("txt.codigo"));
        lNombre.setText(mensajes.getString("txt.nombre"));
        lPrecio.setText(mensajes.getString("producto.precio"));
        lDescripcion.setText(mensajes.getString("producto.detalle"));
        lCategoria.setText(mensajes.getString("producto.categoria"));
        lImagen.setText(mensajes.getString("txt.imagen"));
        bSeleccionar.setText(mensajes.getString("txt.seleccionar"));
        bBuscar.setText(mensajes.getString("boton.buscar"));
        bActualizar.setText(mensajes.getString("boton.actualizar"));
        bCancelar.setText(mensajes.getString("boton.cancelar"));
    }

    public void escogerFoto() {
        selectorImagenes.setFileSelectionMode(JFileChooser.FILES_ONLY);
        FileNameExtensionFilter filtro1 = new FileNameExtensionFilter("*.png", "png");
        FileNameExtensionFilter filtro2 = new FileNameExtensionFilter("*.jpg", "jpg");
        selectorImagenes.setFileFilter(filtro1);
        selectorImagenes.setFileFilter(filtro2);
        try {
            selectorImagenes.showOpenDialog(bActualizar);
            File abre = selectorImagenes.getSelectedFile();
            ruta = abre.getAbsolutePath();
            if (abre != null) {
                FileReader archivos = new FileReader(abre);
                BufferedReader lee = new BufferedReader(archivos);
                lee.close();
            } else {
                ruta = "";
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, ex + ""
                    + "\nNo se ha encontrado el archivo",
                    "ADVERTENCIA!", JOptionPane.WARNING_MESSAGE);
        }
        char c = 92;
        String signo = Character.toString(c);
        tImagen.setText(ruta.replace(signo, "/"));
        lEscogerImg.setIcon(new ImageIcon(tImagen.getText()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectorImagenes = new javax.swing.JFileChooser();
        lCodigo = new javax.swing.JLabel();
        tCodigo = new javax.swing.JTextField();
        tNombre = new javax.swing.JTextField();
        lNombre = new javax.swing.JLabel();
        lPrecio = new javax.swing.JLabel();
        tPrecio = new javax.swing.JTextField();
        tDescripcion = new javax.swing.JTextField();
        lDescripcion = new javax.swing.JLabel();
        lCategoria = new javax.swing.JLabel();
        comboCategoria = new javax.swing.JComboBox<>();
        bActualizar = new javax.swing.JButton();
        bCancelar = new javax.swing.JButton();
        bBuscar = new javax.swing.JButton();
        lImagen = new javax.swing.JLabel();
        tImagen = new javax.swing.JTextField();
        bSeleccionar = new javax.swing.JButton();
        lEscogerImg = new javax.swing.JLabel();

        setClosable(true);
        setTitle(titulo.getText());

        lCodigo.setText("Código:");

        lNombre.setText("Nombre:");

        lPrecio.setText("Precio:");

        lDescripcion.setText("Descripción:");

        lCategoria.setText("Categoría:");

        comboCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { entrada, plato, bebida, postre }));

        bActualizar.setText("Actualizar");
        bActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActualizarActionPerformed(evt);
            }
        });

        bCancelar.setText("Cancelar");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        bBuscar.setText("Buscar");
        bBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarActionPerformed(evt);
            }
        });

        lImagen.setText("Imagen:");

        tImagen.setEditable(false);

        bSeleccionar.setText("Seleccionar...");
        bSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSeleccionarActionPerformed(evt);
            }
        });

        lEscogerImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lEscogerImg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bActualizar)
                        .addGap(18, 18, 18)
                        .addComponent(bCancelar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lCodigo)
                            .addComponent(lDescripcion)
                            .addComponent(lPrecio)
                            .addComponent(lCategoria)
                            .addComponent(lNombre))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bBuscar))
                            .addComponent(tPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(67, 67, 67))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lImagen)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bSeleccionar))
                            .addComponent(lEscogerImg, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lCodigo)
                    .addComponent(bBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNombre)
                    .addComponent(tNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lPrecio)
                    .addComponent(tPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lDescripcion)
                    .addComponent(tDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCategoria)
                    .addComponent(comboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lImagen)
                    .addComponent(tImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bSeleccionar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lEscogerImg, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCancelar)
                    .addComponent(bActualizar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarActionPerformed
        if (tCodigo.getText().equals("") == false) {
            int codigo = Integer.parseInt(tCodigo.getText());
            Producto buscarProducto = controladorProducto.read(codigo);
            if (buscarProducto != null) {
                tNombre.setText(buscarProducto.getNombre());
                tPrecio.setText(Double.toString(buscarProducto.getPrecio()));
                tDescripcion.setText(buscarProducto.getDescripcion());
                comboCategoria.setSelectedItem(buscarProducto.getCategoria().getNombre());
                tImagen.setText(buscarProducto.getImgIcon().toString());
                lEscogerImg.setIcon(buscarProducto.getImgIcon());
                bActualizar.setEnabled(true);
            } else {
                tNombre.setText("");
                tPrecio.setText("");
                tDescripcion.setText("");
                comboCategoria.setSelectedIndex(0);
                tImagen.setText("");
                lEscogerImg.setIcon(null);
                JOptionPane.showMessageDialog(this, nofound = mensajes.getString("option.noprod"), bprod = mensajes.getString("producto.buscar"), JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Error", "Valor", JOptionPane.ERROR_MESSAGE);
            tNombre.setText("");
            tPrecio.setText("");
            tDescripcion.setText("");
            comboCategoria.setSelectedIndex(0);
            tImagen.setText("");
            lEscogerImg.setIcon(null);
        }
    }//GEN-LAST:event_bBuscarActionPerformed

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_bCancelarActionPerformed

    private void bActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActualizarActionPerformed
        int cod = Integer.parseInt(tCodigo.getText());
        Producto productoActual = controladorProducto.read(cod);
        Categoria categoriaPlato = new Categoria();
        categoriaPlato.setNombre("Plato");
        Categoria categoriaBebida = new Categoria();
        categoriaBebida.setNombre("Bebida");
        Categoria categoriaEntrada = new Categoria();
        categoriaEntrada.setNombre("Entrada");
        Categoria categoriaPostre = new Categoria();
        categoriaPostre.setNombre("Postre");
        productoActual.setNombre(tNombre.getText());
        productoActual.setPrecio(Double.parseDouble(tPrecio.getText()));
        productoActual.setDescripcion(tDescripcion.getText());
        String itemSeleccionado = comboCategoria.getSelectedItem().toString();

        comboCategoria.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (itemSeleccionado.equalsIgnoreCase(categoriaEntrada.getNombre())) {
                    productoActual.setCategoria(categoriaEntrada);
                } else if (itemSeleccionado.equalsIgnoreCase(categoriaPlato.getNombre())) {
                    productoActual.setCategoria(categoriaPlato);
                } else if (itemSeleccionado.equalsIgnoreCase(categoriaBebida.getNombre())) {
                    productoActual.setCategoria(categoriaBebida);
                } else if (itemSeleccionado.equalsIgnoreCase(categoriaPostre.getNombre())) {
                    productoActual.setCategoria(categoriaPostre);
                }
            }
        });
        productoActual.setImgIcon(new ImageIcon(tImagen.getText()));
        controladorProducto.update(productoActual);
        JOptionPane.showMessageDialog(this, actpr = mensajes.getString("option.actprod"), titulo.getText(), JOptionPane.YES_NO_OPTION);
        tCodigo.setText("");
        tNombre.setText("");
        tPrecio.setText("");
        tDescripcion.setText("");
        comboCategoria.setSelectedIndex(0);
        tImagen.setText("");
        lEscogerImg.setIcon(null);

    }//GEN-LAST:event_bActualizarActionPerformed

    private void bSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSeleccionarActionPerformed
        selectorImagenes = new JFileChooser();
        selectorImagenes.setVisible(true);
        escogerFoto();
    }//GEN-LAST:event_bSeleccionarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bActualizar;
    private javax.swing.JButton bBuscar;
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bSeleccionar;
    private javax.swing.JComboBox<String> comboCategoria;
    private javax.swing.JLabel lCategoria;
    private javax.swing.JLabel lCodigo;
    private javax.swing.JLabel lDescripcion;
    private javax.swing.JLabel lEscogerImg;
    private javax.swing.JLabel lImagen;
    private javax.swing.JLabel lNombre;
    private javax.swing.JLabel lPrecio;
    private javax.swing.JFileChooser selectorImagenes;
    private javax.swing.JTextField tCodigo;
    private javax.swing.JTextField tDescripcion;
    private javax.swing.JTextField tImagen;
    private javax.swing.JTextField tNombre;
    private javax.swing.JTextField tPrecio;
    // End of variables declaration//GEN-END:variables
}
