/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista.mesero;

import ec.edu.ups.controlador.ControladorMesa;
import ec.edu.ups.controlador.ControladorProducto;
import ec.edu.ups.modelo.Detalle;
import ec.edu.ups.modelo.Mesa;
import ec.edu.ups.modelo.Mesero;
import ec.edu.ups.modelo.Producto;
import ec.edu.ups.modelo.Render;
import java.util.List;
import java.util.Set;
import javax.swing.JButton;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Eduardo Ayora
 */
public class AgregarProducto extends javax.swing.JFrame {

    private ControladorProducto controladorProducto;
    private Mesa mesa;
    private Mesero mesero;
    private ControladorMesa controladorMesa;
    private String nombreCategoria;

    /**
     * Creates new form AgregarProducto
     */
    public AgregarProducto(Mesa mesa, Mesero mesero, ControladorMesa controladorMesa, ControladorProducto controladorProducto) {
        initComponents();
        this.mesa = mesa;
        this.mesero = mesero;
        this.controladorMesa = controladorMesa;
        this.controladorProducto = controladorProducto;
        nombreCategoria = "Platos";
        setLocationRelativeTo(null);
        llenarDatos();
        tblProductos.setRowHeight(60);
    }

    public void llenarDatos() {
        nombreCategoria = "Plato";
        tblProductos.setDefaultRenderer(Object.class, new Render());
        JButton btnSeleccionar = new JButton("Seleccionar");

        List<Producto> productos = controladorProducto.getLista();
        DefaultTableModel modelo = (DefaultTableModel) tblProductos.getModel();
        modelo.setRowCount(0);
        for (Producto producto : productos) {
            if (producto.getCategoria().getNombre().equals("Plato")) {
                Object[] datos = {producto.getCodigoProducto(),
                    producto.getNombre(),
                    producto.getDescripcion(),
                    producto.getPrecio(),
                    producto.getPrecio(),
                    btnSeleccionar
                };
                modelo.addRow(datos);
            }
        }
    }

    private int posicionProducto(int numProducto) {
        int contador = 0;
        int acierto = 0;
        for (int i = 0; i < controladorProducto.getLista().size(); i++) {

            if (!controladorProducto.getLista().get(i).getCategoria().getNombre().equals(nombreCategoria)) {
            } else {
                acierto++;
            }
            if (acierto == numProducto) {
                break;
            }
            contador++;
        }
        return contador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        btnListo = new javax.swing.JButton();

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText("Entradas");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton4.setText("Platos Fuertes");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton2.setText("Bebidas");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton3.setText("Postres");
        jPanel1.add(jButton3);

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Descripción", "Precio", "Fotografía", "Seleccionar"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProductos);

        btnListo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnListo.setText("Listo");
        btnListo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 923, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnListo, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(348, 348, 348))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnListo, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductosMouseClicked
        // TODO add your handling code here:
        int columna = tblProductos.getColumnModel().getColumnIndexAtX(evt.getX());
        int fila = evt.getY() / tblProductos.getRowHeight();

        if (fila < tblProductos.getRowCount() && fila >= 0 && columna < tblProductos.getColumnCount() && columna >= 0) {
            Object value = tblProductos.getValueAt(fila, columna);
            if (value instanceof JButton) {
                ((JButton) value).doClick();
                JButton boton = (JButton) value;
                int numProducto = evt.getY() / tblProductos.getRowHeight();
                int auxNumProducto = posicionProducto(numProducto + 1);
                Producto auxProducto = controladorProducto.getLista().get(auxNumProducto);
                if (boton.isEnabled()) {
                    Detalle detalle = new Detalle();
                    detalle.setCantidad(1);
                    detalle.setPrecio(auxProducto.getPrecio());
                    detalle.setSubtotal(auxProducto.getPrecio());
                    detalle.setProducto(auxProducto);
                    mesa.getControladorDetalle().createFacturaDetalle(detalle);
                }
            }
        }
    }//GEN-LAST:event_tblProductosMouseClicked

    private void btnListoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListoActionPerformed
        // TODO add your handling code here:
        VistaMesa vistaMesa = new VistaMesa(mesa, mesero, controladorMesa, controladorProducto);
        vistaMesa.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnListoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        nombreCategoria = "Plato";
        tblProductos.setDefaultRenderer(Object.class, new Render());
        JButton btnSeleccionar = new JButton("Seleccionar");

        List<Producto> productos = controladorProducto.getLista();
        DefaultTableModel modelo = (DefaultTableModel) tblProductos.getModel();
        modelo.setRowCount(0);
        for (Producto producto : productos) {
            if (producto.getCategoria().getNombre().equals("Plato")) {
                Object[] datos = {producto.getCodigoProducto(),
                    producto.getNombre(),
                    producto.getDescripcion(),
                    producto.getPrecio(),
                    producto.getPrecio(),
                    btnSeleccionar
                };
                modelo.addRow(datos);
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        nombreCategoria = "Bebida";
        tblProductos.setDefaultRenderer(Object.class, new Render());
        JButton btnSeleccionar = new JButton("Seleccionar");

        List<Producto> productos = controladorProducto.getLista();
        DefaultTableModel modelo = (DefaultTableModel) tblProductos.getModel();
        modelo.setRowCount(0);
        for (Producto producto : productos) {
            if (producto.getCategoria().getNombre().equals("Bebida")) {
                Object[] datos = {producto.getCodigoProducto(),
                    producto.getNombre(),
                    producto.getDescripcion(),
                    producto.getPrecio(),
                    producto.getPrecio(),
                    btnSeleccionar
                };
                modelo.addRow(datos);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnListo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProductos;
    // End of variables declaration//GEN-END:variables
}
