/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controlador.ControladorMesero;
import ec.edu.ups.modelo.ClaveCaja;
import ec.edu.ups.modelo.ClaveGerente;
import ec.edu.ups.modelo.Mesero;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;

/**
 *
 * @author Eduardo Ayora
 */
public class CambioContrasenia extends javax.swing.JFrame {

    private ControladorMesero controladorMesero;
    private ClaveGerente claveGerente;
    private ClaveCaja claveCaja;
    private ResourceBundle mensajes;

    /**
     * Creates new form CambioContrasenia
     */
    public CambioContrasenia(ControladorMesero controladorMesero, ClaveGerente claveGerente, ClaveCaja claveCaja, ResourceBundle mensajes) {
        initComponents();
        grupoBotones();
        setLocationRelativeTo(null);
        this.controladorMesero = controladorMesero;
        this.claveGerente = claveGerente;
        this.claveCaja = claveCaja;
        this.mensajes = mensajes;
        cambiarIdioma(mensajes);
    }

    public void grupoBotones() {

        btnGrupo.add(rbtnMesero);
        btnGrupo.add(rbtnCaja);
        btnGrupo.add(rbtnGerente);
        rbtnMesero.setSelected(true);

    }

    public void cambiarIdioma(ResourceBundle mensajes){
        
        rbtnMesero.setText(mensajes.getString("txt.mesero"));
        rbtnCaja.setText(mensajes.getString("txt.caja"));
        rbtnGerente.setText(mensajes.getString("lbl.gerente"));
        lblCodigo.setText(mensajes.getString("cambio.codigo"));
        lblContraseña.setText(mensajes.getString("cambio.contraseña"));
        lblNueva.setText(mensajes.getString("cambio.contraseñanueva"));
        lblNombre.setText(mensajes.getString("txt.nombre"));
        btnCambiar.setText(mensajes.getString("cambio.cambiar"));
        this.repaint();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrupo = new javax.swing.ButtonGroup();
        lblCodigo = new javax.swing.JLabel();
        lblContraseña = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtContraseña = new javax.swing.JPasswordField();
        rbtnMesero = new javax.swing.JRadioButton();
        rbtnCaja = new javax.swing.JRadioButton();
        rbtnGerente = new javax.swing.JRadioButton();
        lblNueva = new javax.swing.JLabel();
        txtNueva = new javax.swing.JPasswordField();
        lblNombre = new javax.swing.JLabel();
        lblNombreMesero = new javax.swing.JLabel();
        btnCambiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblCodigo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCodigo.setText("Ingrese su código:");

        lblContraseña.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblContraseña.setText("Ingrese su contraseña actual:");

        txtCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCodigoFocusLost(evt);
            }
        });

        rbtnMesero.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rbtnMesero.setText("Mesero");
        rbtnMesero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnMeseroActionPerformed(evt);
            }
        });

        rbtnCaja.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rbtnCaja.setText("Caja");
        rbtnCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnCajaActionPerformed(evt);
            }
        });

        rbtnGerente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rbtnGerente.setText("Gerente");
        rbtnGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnGerenteActionPerformed(evt);
            }
        });

        lblNueva.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNueva.setText("Ingrese contraseña nueva:");

        lblNombre.setText("Nombre:");

        btnCambiar.setText("Cambiar Contraseña");
        btnCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtnMesero)
                    .addComponent(rbtnGerente)
                    .addComponent(rbtnCaja))
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNombre)
                        .addGap(18, 18, 18)
                        .addComponent(lblNombreMesero, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(btnCambiar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCodigo)
                            .addComponent(lblNueva))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNueva)
                                .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(16, 16, 16)))
                .addGap(63, 63, 63))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbtnMesero)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnCaja)
                    .addComponent(lblContraseña)
                    .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNueva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbtnGerente)
                        .addComponent(txtNueva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCambiar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(lblNombreMesero, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodigoFocusLost
        // TODO add your handling code here:
        try {
            if (rbtnMesero.isSelected()) {
                Mesero mesero = controladorMesero.read(Integer.parseInt(txtCodigo.getText()));
                lblNombreMesero.setText(mesero.getNombre());
            }
        } catch (Exception ex) {
        }

    }//GEN-LAST:event_txtCodigoFocusLost

    private void rbtnCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnCajaActionPerformed
        // TODO add your handling code here:
        txtCodigo.setEnabled(false);
    }//GEN-LAST:event_rbtnCajaActionPerformed

    private void rbtnMeseroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnMeseroActionPerformed
        // TODO add your handling code here:
        txtCodigo.setEnabled(true);
    }//GEN-LAST:event_rbtnMeseroActionPerformed

    private void rbtnGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnGerenteActionPerformed
        // TODO add your handling code here:
        txtCodigo.setEnabled(false);
    }//GEN-LAST:event_rbtnGerenteActionPerformed

    private void btnCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarActionPerformed
        // TODO add your handling code here:
        String pass = "";
        char[] password = txtContraseña.getPassword();
        for (int i = 0; i < password.length; i++) {
            pass += password[i];
        }
        String contraseñaNueva = new String(txtNueva.getPassword());
        if (rbtnMesero.isSelected()) {
            Mesero mesero = controladorMesero.read(Integer.parseInt(txtCodigo.getText()));
            if (pass.equals(mesero.getContraseña())) {
                if (contraseñaNueva.equals("")) {
                    JOptionPane.showMessageDialog(null, "Campo de contraseña vacia", "Contraseña vacia", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    mesero.setContraseña(contraseñaNueva);
                    JOptionPane.showMessageDialog(null, "Contraseña cambiada exitosamente", "Contraseña correcta", JOptionPane.INFORMATION_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "La contraseña no es correcta", "Contraseña incorrecta", JOptionPane.INFORMATION_MESSAGE);
            }
        }

        if (rbtnCaja.isSelected()) {
            if (pass.equals(claveCaja.getClave())) {
                if (contraseñaNueva.equals("")) {
                    JOptionPane.showMessageDialog(null, "Campo de contraseña vacia", "Contraseña vacia", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    claveCaja.setClave(contraseñaNueva);
                    JOptionPane.showMessageDialog(null, "Contraseña cambiada exitosamente", "Contraseña correcta", JOptionPane.INFORMATION_MESSAGE);
                }
            }else{
                JOptionPane.showMessageDialog(null, "La contraseña no es correcta", "Contraseña incorrecta", JOptionPane.INFORMATION_MESSAGE);
            }
        }

        if (rbtnGerente.isSelected()) {
            if (pass.equals(claveGerente.getClave())) {
                if (contraseñaNueva.equals("")) {
                    JOptionPane.showMessageDialog(null, "Campo de contraseña vacia", "Contraseña vacia", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    claveGerente.setClave(contraseñaNueva);
                    JOptionPane.showMessageDialog(null, "Contraseña cambiada exitosamente", "Contraseña correcta", JOptionPane.INFORMATION_MESSAGE);
                }
            }else{
                JOptionPane.showMessageDialog(null, "La contraseña no es correcta", "Contraseña incorrecta", JOptionPane.INFORMATION_MESSAGE);
            }
        }

    }//GEN-LAST:event_btnCambiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCambiar;
    private javax.swing.ButtonGroup btnGrupo;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombreMesero;
    private javax.swing.JLabel lblNueva;
    private javax.swing.JRadioButton rbtnCaja;
    private javax.swing.JRadioButton rbtnGerente;
    private javax.swing.JRadioButton rbtnMesero;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JPasswordField txtNueva;
    // End of variables declaration//GEN-END:variables
}
