/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.vista.caja.VistaCaja;
import ec.edu.ups.vista.caja.VentanaCrearFactura;
import com.sun.glass.events.KeyEvent;
import ec.edu.ups.controlador.ControladorCliente;
import ec.edu.ups.controlador.ControladorFactura;
import ec.edu.ups.controlador.ControladorMesa;
import ec.edu.ups.modelo.ClaveCaja;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario-Pc
 */
public class ContraseniaCaja extends javax.swing.JFrame {

    public static VistaCaja vistaCaja;
    private ControladorFactura controladorFactura;
    private ControladorCliente controladorCliente;
    private ControladorMesa controladorMesa;
    private VentanaCrearFactura crearFactura;
    private ClaveCaja claveCaja;
    private ResourceBundle mensajes;
    private String aprob;
    private String deneg;
    private String bienvenido;
    private String errorPass;

    /**
     * Creates new form Contrasenia
     */
    public ContraseniaCaja(ControladorFactura controladorFactura,
            ControladorCliente controladorCliente,
            ControladorMesa controladorMesa, ClaveCaja claveCaja,
            VistaCaja vistaCaja, ResourceBundle mensajes) {
        initComponents();
        this.controladorFactura = controladorFactura;
        this.controladorCliente = controladorCliente;
        this.controladorMesa = controladorMesa;
        this.claveCaja = claveCaja;
        this.mensajes = mensajes;
        vistaCaja = this.vistaCaja;
        setLocationRelativeTo(null);
        cambiarIdiomas(mensajes);

    }
    
    public  void cambiarIdiomas(ResourceBundle mensajes){
        lContrasenia.setText(mensajes.getString("txt.contraseña"));
        btnIngresar.setText(mensajes.getString("boton.ingresar"));
         //titulo.setText(mensajes.getString("txt.contraseña"));
        //lContrasena.setText(mensajes.getString("txt.contraseña"));
        btnIngresar.setText(mensajes.getString("boton.ingresar"));
        aprob = mensajes.getString("btn.aceptar");
        deneg = mensajes.getString("btn.aceptar");
        bienvenido = mensajes.getString("jptionp.contrasenia");
        errorPass = mensajes.getString("jptionp.contrasenia.error");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JpassClave = new javax.swing.JPasswordField();
        btnIngresar = new javax.swing.JButton();
        lContrasenia = new javax.swing.JLabel();

        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        JpassClave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JpassClaveKeyPressed(evt);
            }
        });

        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        lContrasenia.setText("Contraseña:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(lContrasenia)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnIngresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JpassClave, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))
                .addGap(113, 113, 113))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JpassClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lContrasenia))
                .addGap(18, 18, 18)
                .addComponent(btnIngresar, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // TODO add your handling code here:
        String aprob;
        String deneg;
        String bienvenido;
        String errorPass;

        char clave[] = JpassClave.getPassword();
        String clavedef = new String(clave);

        if (clavedef.equals(claveCaja.getClave())) {
            this.dispose();
            JOptionPane.showMessageDialog(null,bienvenido = mensajes.getString("jptionp.contrasenia"), 
                    aprob = mensajes.getString("btn.aceptar"), JOptionPane.INFORMATION_MESSAGE);
            
            vistaCaja = new VistaCaja(controladorFactura, controladorCliente, controladorMesa, mensajes);
            vistaCaja.toFront();
            vistaCaja.setVisible(true);
            VentanaPrincipal.vistaCaja = this.vistaCaja;

        } else {
            JOptionPane.showMessageDialog(null, errorPass = mensajes.getString("jptionp.contrasenia.error"), 
                    deneg = mensajes.getString("btn.aceptar"), JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_btnIngresarActionPerformed

    private void JpassClaveKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JpassClaveKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            char clave[] = JpassClave.getPassword();
            String clavedef = new String(clave);

            if (clavedef.equals(claveCaja.getClave())) {

                this.dispose();
                JOptionPane.showMessageDialog(null, "Bienvenido", "mensaje si", JOptionPane.INFORMATION_MESSAGE);
                vistaCaja = new VistaCaja(controladorFactura, controladorCliente, controladorMesa, mensajes);
                vistaCaja.toFront();
                vistaCaja.setVisible(true);
                VentanaPrincipal.vistaCaja = this.vistaCaja;

            } else {
                JOptionPane.showMessageDialog(null, "Error de clave", "mensaje no", JOptionPane.INFORMATION_MESSAGE);
            }
        }

    }//GEN-LAST:event_JpassClaveKeyPressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            this.dispose();
        }
    }//GEN-LAST:event_formKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField JpassClave;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel lContrasenia;
    // End of variables declaration//GEN-END:variables
}
