/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.modelo.Mesero;
import ec.edu.ups.controlador.ControladorMesero;
import java.awt.event.KeyEvent;
import java.util.Set;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class VentanaListaMesero extends javax.swing.JInternalFrame {

    ControladorMesero controladorMesero;

    /**
     * Creates new form VentanaListaMesero
     */
    public VentanaListaMesero(ControladorMesero controladorMesero) {
        initComponents();
        this.controladorMesero = controladorMesero;
        llenarDatos();
    }

    public void llenarDatos() {
        DefaultTableModel modelo = (DefaultTableModel) tablaMesero.getModel();
        Set<Mesero> lista = controladorMesero.getLista();
        for (Mesero mesero : lista) {
            Object[] datos = {mesero.getCodigo(),
                mesero.getCedula(), mesero.getNombre(),
                mesero.getDireccion(), mesero.getTelefono()
            };
            modelo.addRow(datos);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMesero = new javax.swing.JTable();

        setClosable(true);
        setMaximizable(true);
        setTitle("Lista de meseros");
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        tablaMesero.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Cédula", "Nombre", "Dirección", "Teléfono"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaMesero);
        if (tablaMesero.getColumnModel().getColumnCount() > 0) {
            tablaMesero.getColumnModel().getColumn(0).setMinWidth(60);
            tablaMesero.getColumnModel().getColumn(0).setPreferredWidth(60);
            tablaMesero.getColumnModel().getColumn(0).setMaxWidth(60);
            tablaMesero.getColumnModel().getColumn(1).setMinWidth(70);
            tablaMesero.getColumnModel().getColumn(1).setPreferredWidth(70);
            tablaMesero.getColumnModel().getColumn(1).setMaxWidth(70);
            tablaMesero.getColumnModel().getColumn(4).setMinWidth(70);
            tablaMesero.getColumnModel().getColumn(4).setPreferredWidth(70);
            tablaMesero.getColumnModel().getColumn(4).setMaxWidth(70);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE && this.isFocusOwner()) {
            this.dispose();
        }
    }//GEN-LAST:event_formKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaMesero;
    // End of variables declaration//GEN-END:variables
}
