/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controlador.ControladorProducto;
import ec.edu.ups.modelo.Categoria;
import ec.edu.ups.modelo.Producto;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.ResourceBundle;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author DELL
 */
public class VentanaCrearProducto extends javax.swing.JInternalFrame {

    private ControladorProducto controladorProducto;
    private Categoria categoria;
    private String ruta;
    private ResourceBundle mensajes;
    private JLabel titulo;
    private String entrada;
    private String plato;
    private String bebida;
    private String postre;
    private String exito;

    /**
     * Creates new form VentanaCrearProducto
     */
    public VentanaCrearProducto(ControladorProducto controladorProducto, ResourceBundle mensajes) {
        titulo = new JLabel(mensajes.getString("producto.nuevo"));
        entrada = mensajes.getString("txt.entrada");
        plato = mensajes.getString("txt.plato");
        bebida = mensajes.getString("txt.bebida");
        postre = mensajes.getString("txt.postre");
        initComponents();
        this.controladorProducto = controladorProducto;
        this.mensajes = mensajes;
        cambiarIdiomas(mensajes);
        tCodigo.setText(String.valueOf(this.controladorProducto.getCodigo()));

    }

    public void cambiarIdiomas(ResourceBundle mensajes) {
        entrada = mensajes.getString("txt.entrada");
        plato = mensajes.getString("txt.plato");
        bebida = mensajes.getString("txt.bebida");
        postre = mensajes.getString("txt.postre");
        exito = mensajes.getString("option.exitop");
        titulo.setText(mensajes.getString("producto.nuevo"));
        lCodigo.setText(mensajes.getString("txt.codigo"));
        lNombre.setText(mensajes.getString("txt.nombre"));
        lPrecio.setText(mensajes.getString("producto.precio"));
        lDescripcion.setText(mensajes.getString("producto.detalle"));
        lCategoria.setText(mensajes.getString("producto.categoria"));
        lImagen.setText(mensajes.getString("txt.imagen"));
        bSeleccionar.setText(mensajes.getString("txt.seleccionar"));
        bCrear.setText(mensajes.getString("boton.crear"));
        bCancelar.setText(mensajes.getString("boton.cancelar"));
    }

    public void escogerFoto() {
        selecImg.setFileSelectionMode(JFileChooser.FILES_ONLY);
        FileNameExtensionFilter filtro1 = new FileNameExtensionFilter("*.png", "png");
        FileNameExtensionFilter filtro2 = new FileNameExtensionFilter("*.jpg", "jpg");
        selecImg.setFileFilter(filtro1);
        selecImg.setFileFilter(filtro2);
        try {
            selecImg.showOpenDialog(bCrear);
            File abre = selecImg.getSelectedFile();
            ruta = abre.getAbsolutePath();
            if (abre != null) {
                FileReader archivos = new FileReader(abre);
                BufferedReader lee = new BufferedReader(archivos);
                lee.close();
                
            }else{
                ruta = "";
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, ex + ""
                    + "\nNo se ha encontrado el archivo",
                    "ADVERTENCIA!", JOptionPane.WARNING_MESSAGE);
        }
        char c = 92;
        String signo = Character.toString(c);
        tImagen.setText(ruta.replace(signo, "/"));
        lEscogerImg.setIcon(new ImageIcon(tImagen.getText()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selecImg = new javax.swing.JFileChooser();
        tCodigo = new javax.swing.JTextField();
        lCodigo = new javax.swing.JLabel();
        lNombre = new javax.swing.JLabel();
        tNombre = new javax.swing.JTextField();
        tPrecio = new javax.swing.JTextField();
        lPrecio = new javax.swing.JLabel();
        lDescripcion = new javax.swing.JLabel();
        tDescripcion = new javax.swing.JTextField();
        lCategoria = new javax.swing.JLabel();
        bCrear = new javax.swing.JButton();
        bCancelar = new javax.swing.JButton();
        comboCategoria = new javax.swing.JComboBox<>();
        lImagen = new javax.swing.JLabel();
        tImagen = new javax.swing.JTextField();
        bSeleccionar = new javax.swing.JButton();
        lEscogerImg = new javax.swing.JLabel();

        setClosable(true);
        setTitle(titulo.getText());
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        tCodigo.setEditable(false);

        lCodigo.setText("Código:");

        lNombre.setText("Nombre:");

        lPrecio.setText("Precio:");

        lDescripcion.setText("Descripción:");

        lCategoria.setText("Categoría:");

        bCrear.setText("Crear");
        bCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCrearActionPerformed(evt);
            }
        });

        bCancelar.setText("Cancelar");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        comboCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { entrada, plato, bebida, postre }));

        lImagen.setText("Imagen:");

        tImagen.setEditable(false);

        bSeleccionar.setText("Seleccionar...");
        bSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSeleccionarActionPerformed(evt);
            }
        });

        lEscogerImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lEscogerImg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lImagen)
                    .addComponent(lCodigo)
                    .addComponent(lDescripcion)
                    .addComponent(lPrecio)
                    .addComponent(lCategoria)
                    .addComponent(lNombre))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bCrear)
                        .addGap(18, 18, 18)
                        .addComponent(bCancelar))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tCodigo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tPrecio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tDescripcion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lEscogerImg, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bSeleccionar)))
                        .addGap(0, 12, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lCodigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNombre)
                    .addComponent(tNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lPrecio)
                    .addComponent(tPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lDescripcion)
                    .addComponent(tDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCategoria)
                    .addComponent(comboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lImagen)
                    .addComponent(bSeleccionar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lEscogerImg, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCancelar)
                    .addComponent(bCrear))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            this.dispose();
        }
    }//GEN-LAST:event_formKeyPressed

    private void bCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCrearActionPerformed
        Producto producto = new Producto();
        Categoria categoriaPlato = new Categoria();
        categoriaPlato.setNombre("Plato");
        Categoria categoriaBebida = new Categoria();
        categoriaBebida.setNombre("Bebida");
        Categoria categoriaEntrada = new Categoria();
        categoriaEntrada.setNombre("Entrada");
        Categoria categoriaPostre = new Categoria();
        categoriaPostre.setNombre("Postre");
        producto.setCodigoProducto(Integer.parseInt(tCodigo.getText()));
        producto.setNombre(tNombre.getText());
        producto.setPrecio(Double.parseDouble(tPrecio.getText()));
        producto.setDescripcion(tDescripcion.getText());
        int itemSeleccionado = comboCategoria.getSelectedIndex();

        comboCategoria.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (itemSeleccionado==0) {
                    producto.setCategoria(categoriaEntrada);
                } else if (itemSeleccionado==1) {
                    producto.setCategoria(categoriaPlato);
                } else if (itemSeleccionado==2) {
                    producto.setCategoria(categoriaBebida);
                } else if (itemSeleccionado==3) {
                    producto.setCategoria(categoriaPostre);
                }
            }
        });
        producto.setImgIcon(new ImageIcon(tImagen.getText()));
        controladorProducto.create(producto);
        JOptionPane.showMessageDialog(this, exito = mensajes.getString("option.exitop"), titulo.getText(), JOptionPane.YES_OPTION);
        tCodigo.setText(String.valueOf(this.controladorProducto.getCodigo()));
        tNombre.setText("");
        tPrecio.setText("");
        tDescripcion.setText("");
        comboCategoria.setSelectedIndex(0);
        tImagen.setText("");
        lEscogerImg.setIcon(null);
    }//GEN-LAST:event_bCrearActionPerformed

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_bCancelarActionPerformed

    private void bSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSeleccionarActionPerformed
        selecImg = new JFileChooser();
        selecImg.setVisible(true);
        escogerFoto();

    }//GEN-LAST:event_bSeleccionarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bCrear;
    private javax.swing.JButton bSeleccionar;
    private javax.swing.JComboBox<String> comboCategoria;
    private javax.swing.JLabel lCategoria;
    private javax.swing.JLabel lCodigo;
    private javax.swing.JLabel lDescripcion;
    private javax.swing.JLabel lEscogerImg;
    private javax.swing.JLabel lImagen;
    private javax.swing.JLabel lNombre;
    private javax.swing.JLabel lPrecio;
    private javax.swing.JFileChooser selecImg;
    private javax.swing.JTextField tCodigo;
    private javax.swing.JTextField tDescripcion;
    private javax.swing.JTextField tImagen;
    private javax.swing.JTextField tNombre;
    private javax.swing.JTextField tPrecio;
    // End of variables declaration//GEN-END:variables
}
