/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controlador.ControladorMesa;
import ec.edu.ups.controlador.ControladorMesero;
import ec.edu.ups.controlador.ControladorProducto;
import ec.edu.ups.modelo.ImagenFondoGerente;
import java.awt.Dimension;
import java.awt.event.KeyEvent;

/**
 *
 * @author DELL
 */
public class VistaGerente extends javax.swing.JFrame {

    private VentanaCrearMesero vcm;
    private VentanaEditarMesero vem;
    private VentanaBuscarMesero vbm;
    private VentanaEliminarMesero vem1;
    private VentanaListaMesero vlm;
    private VentanaCrearProducto vcp;
    private VentanaBuscarProducto vbp;
    private VentanaEditarProducto vep;
    private VentanaEliminarProducto vep1;
    private VentanaListaProducto vlp;
    private ControladorProducto cp;
    private ControladorMesero cm;
    private ControladorMesa cm1;

    /**
     * Creates new form VistaGerente
     */
    public VistaGerente(ControladorProducto cp, ControladorMesero cm, ControladorMesa cm1) {
        initComponents();
        jDesktopPane1.setBorder(new ImagenFondoGerente());
        this.setExtendedState(VistaGerente.MAXIMIZED_BOTH);
        this.cp = cp;
        this.cm = cm;
        this.cm1 = cm1;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menMesero = new javax.swing.JMenu();
        opCrearMe = new javax.swing.JMenuItem();
        opReadMe = new javax.swing.JMenuItem();
        opUpdateMe = new javax.swing.JMenuItem();
        opDeleteMe = new javax.swing.JMenuItem();
        opListMe = new javax.swing.JMenuItem();
        menMesa = new javax.swing.JMenu();
        opCrearMesa = new javax.swing.JMenuItem();
        opReadMesa = new javax.swing.JMenuItem();
        opUpdateMesa = new javax.swing.JMenuItem();
        opDeleteMesa = new javax.swing.JMenuItem();
        opListMesa = new javax.swing.JMenuItem();
        menProduct = new javax.swing.JMenu();
        opCrearP = new javax.swing.JMenuItem();
        opReadP = new javax.swing.JMenuItem();
        opUpdateP = new javax.swing.JMenuItem();
        opDeleteP = new javax.swing.JMenuItem();
        opListP = new javax.swing.JMenuItem();

        setTitle("Gestión de Gerente");
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 324, Short.MAX_VALUE)
        );

        menMesero.setText("Mesero");

        opCrearMe.setText("Nuevo");
        menMesero.add(opCrearMe);

        opReadMe.setText("Buscar");
        menMesero.add(opReadMe);

        opUpdateMe.setText("Editar");
        menMesero.add(opUpdateMe);

        opDeleteMe.setText("Eliminar");
        menMesero.add(opDeleteMe);

        opListMe.setText("Lista");
        menMesero.add(opListMe);

        jMenuBar1.add(menMesero);

        menMesa.setText("Mesa");

        opCrearMesa.setText("Nuevo");
        menMesa.add(opCrearMesa);

        opReadMesa.setText("Buscar");
        menMesa.add(opReadMesa);

        opUpdateMesa.setText("Editar");
        menMesa.add(opUpdateMesa);

        opDeleteMesa.setText("Eliminar");
        menMesa.add(opDeleteMesa);

        opListMesa.setText("Lista");
        menMesa.add(opListMesa);

        jMenuBar1.add(menMesa);

        menProduct.setText("Producto");

        opCrearP.setText("Nuevo");
        menProduct.add(opCrearP);

        opReadP.setText("Buscar");
        menProduct.add(opReadP);

        opUpdateP.setText("Editar");
        menProduct.add(opUpdateP);

        opDeleteP.setText("Eliminar");
        menProduct.add(opDeleteP);

        opListP.setText("Lista");
        menProduct.add(opListP);

        jMenuBar1.add(menProduct);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opCrearMeActionPerformed(java.awt.event.ActionEvent evt) {                                          
            jDesktopPane1.removeAll();
            jDesktopPane1.repaint();
            vcm = new VentanaCrearMesero();
            vcm.toFront();
            vcm.setVisible(true);
            jDesktopPane1.add(vcm);
            Dimension desktopSize = jDesktopPane1.getSize();
            Dimension frameSize = vcm.getSize();
            vcm.setLocation((desktopSize.width - frameSize.width) / 2, (desktopSize.height - frameSize.height) / 2);
            vcm.toFront();
        
    }                                         

    private void opReadPActionPerformed(java.awt.event.ActionEvent evt) {                                        
            jDesktopPane1.removeAll();
            jDesktopPane1.repaint();
            vbp = new VentanaBuscarProducto(cp);
            vbp.toFront();
            vbp.setVisible(true);
            jDesktopPane1.add(vbp);
            Dimension desktopSize = jDesktopPane1.getSize();
            Dimension frameSize = vbp.getSize();
            vbp.setLocation((desktopSize.width - frameSize.width) / 2, (desktopSize.height - frameSize.height) / 2);
        
            vbp.toFront();
        
    }                                       

    private void opReadCaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opReadCaActionPerformed

    }//GEN-LAST:event_opReadCaActionPerformed

    private void opReadMesaActionPerformed(java.awt.event.ActionEvent evt) {                                           

    }                                          

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            this.dispose();
        }
    }//GEN-LAST:event_formKeyPressed

    private void opReadMeActionPerformed(java.awt.event.ActionEvent evt) {                                         
            jDesktopPane1.removeAll();
            jDesktopPane1.repaint();
            vbm = new VentanaBuscarMesero();
            vbm.toFront();
            vbm.setVisible(true);
            jDesktopPane1.add(vbm);
            Dimension desktopSize = jDesktopPane1.getSize();
            Dimension frameSize = vbm.getSize();
            vbm.setLocation((desktopSize.width - frameSize.width) / 2, (desktopSize.height - frameSize.height) / 2);
            vbm.toFront();
        
    }                                        

    private void opUpdateMeActionPerformed(java.awt.event.ActionEvent evt) {                                           
            jDesktopPane1.removeAll();
            jDesktopPane1.repaint();
            vem = new VentanaEditarMesero();
            vem.toFront();
            vem.setVisible(true);
            jDesktopPane1.add(vem);
            Dimension desktopSize = jDesktopPane1.getSize();
            Dimension frameSize = vem.getSize();
            vem.setLocation((desktopSize.width - frameSize.width) / 2, (desktopSize.height - frameSize.height) / 2);
            vem.toFront();
        
    }                                          

    private void opDeleteMeActionPerformed(java.awt.event.ActionEvent evt) {                                           
            jDesktopPane1.removeAll();
            jDesktopPane1.repaint();
            vem1 = new VentanaEliminarMesero();
            vem1.toFront();
            vem1.setVisible(true);
            jDesktopPane1.add(vem1);
            Dimension desktopSize = jDesktopPane1.getSize();
            Dimension frameSize = vem1.getSize();
            vem1.setLocation((desktopSize.width - frameSize.width) / 2, (desktopSize.height - frameSize.height) / 2);
            vem1.toFront();
        
    }                                          

    private void opListMeActionPerformed(java.awt.event.ActionEvent evt) {                                         
            jDesktopPane1.removeAll();
            jDesktopPane1.repaint();
            vlm = new VentanaListaMesero();
            vlm.toFront();
            vlm.setVisible(true);
            jDesktopPane1.add(vlm);
            Dimension desktopSize = jDesktopPane1.getSize();
            Dimension frameSize = vlm.getSize();
            vlm.setLocation((desktopSize.width - frameSize.width) / 2, (desktopSize.height - frameSize.height) / 2);
            vlm.toFront();
        
    }                                        

    private void opCrearPActionPerformed(java.awt.event.ActionEvent evt) {                                         
            jDesktopPane1.removeAll();
            jDesktopPane1.repaint();
            vcp = new VentanaCrearProducto(cp);
            vcp.toFront();
            vcp.setVisible(true);
            jDesktopPane1.add(vcp);
            Dimension desktopSize = jDesktopPane1.getSize();
            Dimension frameSize = vcp.getSize();
            vcp.setLocation((desktopSize.width - frameSize.width) / 2, (desktopSize.height - frameSize.height) / 2);
            vcp.toFront();
        

    }                                        

    private void opUpdatePActionPerformed(java.awt.event.ActionEvent evt) {                                          
            jDesktopPane1.removeAll();
            jDesktopPane1.repaint();
            vep = new VentanaEditarProducto(cp);
            vep.toFront();
            vep.setVisible(true);
            jDesktopPane1.add(vep);
            Dimension desktopSize = jDesktopPane1.getSize();
            Dimension frameSize = vep.getSize();
            vep.setLocation((desktopSize.width - frameSize.width) / 2, (desktopSize.height - frameSize.height) / 2);
            vep.toFront();
        
    }                                         

    private void opDeletePActionPerformed(java.awt.event.ActionEvent evt) {                                          
            jDesktopPane1.removeAll();
            jDesktopPane1.repaint();
            vep1 = new VentanaEliminarProducto();
            vep1.toFront();
            vep1.setVisible(true);
            jDesktopPane1.add(vep1);
            Dimension desktopSize = jDesktopPane1.getSize();
            Dimension frameSize = vep1.getSize();
            vep1.setLocation((desktopSize.width - frameSize.width) / 2, (desktopSize.height - frameSize.height) / 2);
            vep1.toFront();
        
    }                                         


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menMesa;
    private javax.swing.JMenu menMesero;
    private javax.swing.JMenu menProduct;
    private javax.swing.JMenuItem opCrearMe;
    private javax.swing.JMenuItem opCrearMesa;
    private javax.swing.JMenuItem opCrearP;
    private javax.swing.JMenuItem opDeleteMe;
    private javax.swing.JMenuItem opDeleteMesa;
    private javax.swing.JMenuItem opDeleteP;
    private javax.swing.JMenuItem opListMe;
    private javax.swing.JMenuItem opListMesa;
    private javax.swing.JMenuItem opListP;
    private javax.swing.JMenuItem opReadMe;
    private javax.swing.JMenuItem opReadMesa;
    private javax.swing.JMenuItem opReadP;
    private javax.swing.JMenuItem opUpdateMe;
    private javax.swing.JMenuItem opUpdateMesa;
    private javax.swing.JMenuItem opUpdateP;
    // End of variables declaration//GEN-END:variables
}
